export const subjects = [
  {
    id: 'rbh',
    name: 'Rechtsbewusstes Handeln',
    shortName: 'RBH',
    color: 'blue',
    colorClass: 'bg-blue-600',
    colorClassLight: 'bg-blue-50',
    textClass: 'text-blue-600',
    borderClass: 'border-blue-600',
    icon: '⚖️',
    questionCount: 5,
  },
  {
    id: 'bwh',
    name: 'Betriebswirtschaftliches Handeln',
    shortName: 'BWH',
    color: 'emerald',
    colorClass: 'bg-emerald-600',
    colorClassLight: 'bg-emerald-50',
    textClass: 'text-emerald-600',
    borderClass: 'border-emerald-600',
    icon: '📊',
    questionCount: 5,
  },
  {
    id: 'ikp',
    name: 'Information, Kommunikation, Planung',
    shortName: 'IKP',
    color: 'violet',
    colorClass: 'bg-violet-600',
    colorClassLight: 'bg-violet-50',
    textClass: 'text-violet-600',
    borderClass: 'border-violet-600',
    icon: '💬',
    questionCount: 5,
  },
  {
    id: 'zib',
    name: 'Zusammenarbeit im Betrieb',
    shortName: 'ZIB',
    color: 'amber',
    colorClass: 'bg-amber-600',
    colorClassLight: 'bg-amber-50',
    textClass: 'text-amber-600',
    borderClass: 'border-amber-600',
    icon: '🤝',
    questionCount: 5,
  },
  {
    id: 'ntg',
    name: 'Naturwiss. & techn. Gesetzmäßigkeiten',
    shortName: 'NTG',
    color: 'red',
    colorClass: 'bg-red-600',
    colorClassLight: 'bg-red-50',
    textClass: 'text-red-600',
    borderClass: 'border-red-600',
    icon: '🔬',
    questionCount: 5,
  },
]

export function getSubject(id) {
  return subjects.find((s) => s.id === id)
}
